language: rust
dist: trusty
rust: 
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly

sudo: required

cache: cargo

os: 
  - linux


after_success: |
  [ $TRAVIS_BRANCH = master ] &&
  [ $TRAVIS_PULL_REQUEST = false ] &&
  cargo doc &&
  echo "<meta http-equiv=refresh content=0;url=/llvm-rs/llvm/index.html>" > target/doc/index.html &&
  sudo pip install ghp-import &&
  ghp-import -n target/doc &&
  git push -fq https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git gh-pages
before_install:
  - ((cargo install cargo-travis &&  cargo install rustfmt-nightly) || true)
  - sudo sh -c "add-apt-repository -y ppa:ubuntu-toolchain-r/test"
  - sudo sh -c "echo 'deb http://llvm.org/apt/precise/ llvm-toolchain-precise-4.0 main' >> /etc/apt/sources.list"
  - wget -O - http://llvm.org/apt/llvm-snapshot.gpg.key | sudo apt-key add -
install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq llvm-4.0 libllvm4.0 libllvm4.0-dbg cmake libedit-dev
  - sudo ln -s /usr/bin/llvm-config-4.0 /usr/local/bin/llvm-config
  - llvm-config-4.0 --version
script:
  - cargo clean
  - cargo build --verbose
  - cargo test --verbose
  - cargo bench --verbose
  - cargo run --example tan
  - cargo run --example fib
  - cargo run --example add
  - cargo run --example add3
  - cargo run --example pass_manager
  - cargo run --example demo_3f
  
